### ISSUE TITLE
gobuster and amass installs fail with current Go version

### ISSUE THREAD

**Issue by derpadoo** [epi052/recon-pipeline#101]
https://github.com/epi052/recon-pipeline/blob/30a90a479b99d987f133dcc2b539ed57127fdeba/pipeline/tools/go.yaml#L3

Changed to "https://dl.google.com/go/go1.16.3.linux-" and installation worked.

**Comment by epi052** [comment]
yup, the installer basically gets hosed with each release :cry: to really fix this, there needs to be a function that reaches out to the golang download page and figures out what the latest version is before grabbing it. For w/e reason, there isn't a /latest/ link or similar, and i never got around to making it dynamic.

**Comment by epi052** [comment]
i can knock this out quick, no guarantees can be made if they change the url/page etc since ill have to grab it from the source

**Comment by epi052** [comment]
fixed in  0bdfa45cf870b8e6a40ec21d6832a3852ae0afde :smile:
