### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by dol0han** [epi052/recon-pipeline#109]
**the bug**
installed python3.7, configured it with openssl(just installed it from source too), when install dependencies using "pipenv install" I get the error below stating "There was a problem confirming the ssl certificate"

**To Reproduce**
1. pipenv install

**Expected behavior**
dependencies to be installed in a virtualenv, i guess.

**Traceback / Error Output**
Installing dependencies from Pipfile.lock (e32771)...
An error occurred while installing docutils==0.15.2 --hash=sha256:a2aeea129088da402665e92e0b25b04b073c04b2dce4ab65caaa38b7ce2e1a99 --hash=sha256:6c4f696463b79f1fb8ba0c594b63840ebd41f059e92b31957c46b74a4599b6d0 --hash=sha256:9e4d7ecfc600058e07ba661411a2b7de2fd0fafa17d1a7f7361cd47b1175c827! Will try again.
An error occurred while installing lockfile==0.12.2 --hash=sha256:6aed02de03cba24efabcd600b30540140634fc06cfa603822d508d5361e9f799 --hash=sha256:6c3cb24f344923d30b2785d5ad75182c8ea7ac1b6171b08657258ec7429d50fa! Will try again.
An error occurred while installing luigi==2.8.9 --hash=sha256:ac8d6f25a417498f09bbf79ab7ea4d9f16d431cf5015ed03fbf489307f3ea661! Will try again.
An error occurred while installing python-daemon==2.1.2 --hash=sha256:53da55aec3bb67b576e13a8091a2181f99b395c2eec32a5a0d91d347a5c420a7 --hash=sha256:261c859be5c12ae7d4286dc6951e87e9e1a70a882a8b41fd926efc1ec4214f73! Will try again.
An error occurred while installing python-dateutil==2.8.0 --hash=sha256:7e6584c74aeed623791615e26efd690f29817a27c73085b78e4bad02493df2fb --hash=sha256:c89805f6f4d64db21ed966fda138f8a5ed7a4fdbc1a8ee329ce1b74e3c74da9e! Will try again.
An error occurred while installing six==1.12.0 --hash=sha256:3350809f0555b11f552448330d0b52d5f24c91a322ea4a15ef22629740f3761c --hash=sha256:d16a0141ec1a18405cd4ce8b4613101da75da0e9a7aec5bdd4fa804d0e0eba73! Will try again.
An error occurred while installing tornado==5.1.1 --hash=sha256:4e5158d97583502a7e2739951553cbd88a72076f152b4b11b64b9a10c4c49409 --hash=sha256:8154ec22c450df4e06b35f131adc4f2f3a12ec85981a203301d310abf580500f --hash=sha256:8e9d728c4579682e837c92fdd98036bd5cdefa1da2aaf6acf26947e6dd0c01c5 --hash=sha256:d4b3e5329f572f055b587efc57d29bd051589fb5a43ec8898c77a47ec2fa2bbb --hash=sha256:0662d28b1ca9f67108c7e3b77afabfb9c7e87bde174fbda78186ecedc2499a9d --hash=sha256:732e836008c708de2e89a31cb2fa6c0e5a70cb60492bee6f1ea1047500feaf7f --hash=sha256:e5f2585afccbff22390cddac29849df463b252b711aa2ce7c5f3f342a5b3b444! Will try again.
Installing initially failed dependencies...
[pipenv.exceptions.InstallError]: Could not fetch URL https://pypi.org/simple/docutils/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/docutils/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
[pipenv.exceptions.InstallError]: WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
[pipenv.exceptions.InstallError]: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/docutils/
[pipenv.exceptions.InstallError]: WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/docutils/
[pipenv.exceptions.InstallError]: WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/docutils/
[pipenv.exceptions.InstallError]: WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/docutils/
[pipenv.exceptions.InstallError]: WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/docutils/
[pipenv.exceptions.InstallError]: ERROR: Could not find a version that satisfies the requirement docutils==0.15.2 (from versions: none)
[pipenv.exceptions.InstallError]: ERROR: No matching distribution found for docutils==0.15.2
ERROR: Couldn't install package: [Requirement(_name='docutils', vcs=None, req=NamedRequirement(name='docutils', version='==0.15.2', req=Requirement.parse('docutils==0.15.2'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=docutils, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===0.15.2, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=docutils==0.15.2)>), markers=None, _specifiers='==0.15.2', index=None, editable=False, hashes=frozenset({'sha256:a2aeea129088da402665e92e0b25b04b073c04b2dce4ab65caaa38b7ce2e1a99', 'sha256:6c4f696463b79f1fb8ba0c594b63840ebd41f059e92b31957c46b74a4599b6d0', 'sha256:9e4d7ecfc600058e07ba661411a2b7de2fd0fafa17d1a7f7361cd47b1175c827'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=docutils, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===0.15.2, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=docutils==0.15.2)>, _ireq=None), Requirement(_name='lockfile', vcs=None, req=NamedRequirement(name='lockfile', version='==0.12.2', req=Requirement.parse('lockfile==0.12.2'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=lockfile, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===0.12.2, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=lockfile==0.12.2)>), markers=None, _specifiers='==0.12.2', index=None, editable=False, hashes=frozenset({'sha256:6aed02de03cba24efabcd600b30540140634fc06cfa603822d508d5361e9f799', 'sha256:6c3cb24f344923d30b2785d5ad75182c8ea7ac1b6171b08657258ec7429d50fa'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=lockfile, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===0.12.2, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=lockfile==0.12.2)>, _ireq=None), Requirement(_name='luigi', vcs=None, req=NamedRequirement(name='luigi', version='==2.8.9', req=Requirement.parse('luigi==2.8.9'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=luigi, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===2.8.9, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=luigi==2.8.9)>), markers=None, _specifiers='==2.8.9', index='pypi', editable=False, hashes=frozenset({'sha256:ac8d6f25a417498f09bbf79ab7ea4d9f16d431cf5015ed03fbf489307f3ea661'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=luigi, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===2.8.9, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=luigi==2.8.9)>, _ireq=None), Requirement(_name='python-daemon', vcs=None, req=NamedRequirement(name='python-daemon', version='==2.1.2', req=Requirement.parse('python-daemon==2.1.2'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=python-daemon, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===2.1.2, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=python-daemon==2.1.2)>), markers=None, _specifiers='==2.1.2', index=None, editable=False, hashes=frozenset({'sha256:53da55aec3bb67b576e13a8091a2181f99b395c2eec32a5a0d91d347a5c420a7', 'sha256:261c859be5c12ae7d4286dc6951e87e9e1a70a882a8b41fd926efc1ec4214f73'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=python-daemon, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===2.1.2, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=python-daemon==2.1.2)>, _ireq=None), Requirement(_name='python-dateutil', vcs=None, req=NamedRequirement(name='python-dateutil', version='==2.8.0', req=Requirement.parse('python-dateutil==2.8.0'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=python-dateutil, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===2.8.0, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=python-dateutil==2.8.0)>), markers=None, _specifiers='==2.8.0', index=None, editable=False, hashes=frozenset({'sha256:7e6584c74aeed623791615e26efd690f29817a27c73085b78e4bad02493df2fb', 'sha256:c89805f6f4d64db21ed966fda138f8a5ed7a4fdbc1a8ee329ce1b74e3c74da9e'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=python-dateutil, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===2.8.0, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=python-dateutil==2.8.0)>, _ireq=None), Requirement(_name='six', vcs=None, req=NamedRequirement(name='six', version='==1.12.0', req=Requirement.parse('six==1.12.0'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=six, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===1.12.0, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=six==1.12.0)>), markers=None, _specifiers='==1.12.0', index=None, editable=False, hashes=frozenset({'sha256:3350809f0555b11f552448330d0b52d5f24c91a322ea4a15ef22629740f3761c', 'sha256:d16a0141ec1a18405cd4ce8b4613101da75da0e9a7aec5bdd4fa804d0e0eba73'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=six, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===1.12.0, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=six==1.12.0)>, _ireq=None), Requirement(_name='tornado', vcs=None, req=NamedRequirement(name='tornado', version='==5.1.1', req=Requirement.parse('tornado==5.1.1'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=tornado, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===5.1.1, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=tornado==5.1.1)>), markers=None, _specifiers='==5.1.1', index=None, editable=False, hashes=frozenset({'sha256:4e5158d97583502a7e2739951553cbd88a72076f152b4b11b64b9a10c4c49409', 'sha256:8154ec22c450df4e06b35f131adc4f2f3a12ec85981a203301d310abf580500f', 'sha256:8e9d728c4579682e837c92fdd98036bd5cdefa1da2aaf6acf26947e6dd0c01c5', 'sha256:d4b3e5329f572f055b587efc57d29bd051589fb5a43ec8898c77a47ec2fa2bbb', 'sha256:0662d28b1ca9f67108c7e3b77afabfb9c7e87bde174fbda78186ecedc2499a9d', 'sha256:732e836008c708de2e89a31cb2fa6c0e5a70cb60492bee6f1ea1047500feaf7f', 'sha256:e5f2585afccbff22390cddac29849df463b252b711aa2ce7c5f3f342a5b3b444'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=tornado, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===5.1.1, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=tornado==5.1.1)>, _ireq=None)]
 Package installation failed...

**Environment (please complete the following information):**
 - recon-pipeline version: v0.9.1
 - python version 3.7
 - OS Kali latest

**Additional context**

**Comment by NotoriousRebel** [comment]
@dol0han Have you figured out a possible fix? Have you tried with a more recent version of python?

**Comment by epi052** [comment]
looks like your python install doesn't know about your openssl

you can try either
- installing libssl/openssl via a package manager 
- upgrading to python3.10 and installing https://pypi.org/project/truststore/
