### ISSUE TITLE
add reinstall command

### ISSUE THREAD

**Issue by epi052** [epi052/recon-pipeline#22]
A nice quality of life improvement would be to add a `reinstall` command.  

Should
- remove old installation
- call install for that tool

Blocked by:
- https://github.com/epi052/recon-pipeline/projects/4#card-36512722

**Comment by GreaterGoodest** [comment]
Working this

**Comment by epi052** [comment]
There's a wrapper for this in the wip pr.  How do you feel about working both off of the add-tools-command branch?

**Comment by GreaterGoodest** [comment]
Sure, I'll rebase that branch and work from there

**Comment by epi052** [comment]
closed in #60
