### ISSUE TITLE
no chrome installed on cloud hosts -> no aquatone results

### ISSUE THREAD

**Issue by epi052** [epi052/recon-pipeline#26]
Installing all dependencies on a (tested digitalocean) VPS does not take care of aquatone's chrome dependency.  

Could look at installing headless chrome or phantomJS as part of the install command if it's not there.

**Comment by opsdisk** [comment]
`apt install chromium-browser` worked for me for Ubuntu 18.04.

**Comment by epi052** [comment]
> `apt install chromium-browser` worked for me for Ubuntu 18.04.

these are the commands i'm tracking to install on DO's ubuntu 18.04.3 droplet

```
sudo add-apt-repository ppa:canonical-chromium-builds/stage
sudo apt-get update
sudo apt-get install chromium-browser 
```

Need to find a universal way of checking whether aquatone can run, might be as simple as running it and checking for failure.

**Comment by opsdisk** [comment]
I didn't have to add the ppa repo at all.  For aquatone, specify the path `-chrome-path /usr/bin/chromium-browser`

**Comment by epi052** [comment]
you're right, spun up another droplet to confirm.  I must have forgotten to run update before checking for the chromium-browser package the first time around.

**Comment by AbdulConsole** [comment]
i am trying to use this tool on a window 10 os, i get this error

Unable to locate a valid installation of Chrome. Install Google Chrome or try specifying a valid location with the -chrome-path option.

**Comment by Forlay** [comment]
Try this `apt-get install chromium -y`
