### ISSUE TITLE
MasscanScan shouldn't fail unclearly when default results directory exists

### ISSUE THREAD

**Issue by GreaterGoodest** [epi052/recon-pipeline#30]
Notify user when unable to complete scan due to default results directory existing.

Additionally: prompt with option to overwrite this directory, or inform them of parameter to use to write somewhere else (--results-dir)

**Comment by epi052** [comment]
I agree that seeing Failed Dependencies when running a scan with existing results is confusing as it's not really clear what is going on without understanding how Luigi works.  

Some of the things that need to be conveyed:
- let user know that they're scanning using an existing directory
- explain that subfolders/files may tell the pipeline that the associated Task is complete and won't be performed again
    - this is especially important in the case of scans with no results found

Could use self.select (see database attach for an example) to offer options for moving forward
1. proceeed anyway
2. remove directory and rescan
3. use new folder (prompt for new folder)
