### ISSUE TITLE
using command "view endpoints --paged  --status-code 403" get error

### ISSUE THREAD

**Issue by briefcasehi** [epi052/recon-pipeline#34]
Error: argument --status-code: invalid choice: '403' (choose from )

**Comment by epi052** [comment]
Two questions:
- Can you confirm that there are 403 entries to be found by running `view endpoints`
- If there are, can you close the shell and reopen/reattach to your database and check if the problem persists?

**Comment by briefcasehi** [comment]
Thanks. Solving the problem by reopening the database.
