### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by bamhm182** [epi052/recon-pipeline#62]
**Problem**
I blow away my OS's a lot, it'd be nice to not have to set this tool up each time or worry about dependencies, even if it is very easy to set it up.

**Solution**
I'd like to be able to pull a Docker Image to my workstation whenever I need this tool.

**Additional context**
I'll start working on the Dockerfile and submit a PR for this. Just adding an issue mostly for tracking purposes.

I'm currently considering having a few volumes that would be passed through for this Image, such as the following:

* Tools: Directory where tools are installed so they're managed/can be added to outside of the container
* Scopes: Directory containing scope files so they're not blown away when the container is recreated
* Databases: Same reasoning as above, but for the databases

If you have anything else you want me to take into consideration while working on this, please mention it in this thread.

**Comment by epi052** [comment]
Sounds great, thank you!

**Comment by bamhm182** [comment]
I was just checking through my many unread emails and just saw this. Sorry I never got around to submitting a PR for it, especially considering it was basically done. I saw you had a couple changes in dependency handling coming soon so I figured I'd wait for a second and then it totally fell off my radar. I've been meaning to revisit it but haven't found the time. I'll make time to do a thorough check that everything is working properly and update the docs as you've requested. Sorry again for the delay!

**Comment by epi052** [comment]
No need to be sorry.  Thank you!

**Comment by epi052** [comment]
Everything looks good.  I'm pretty sure `eth0` is going to be dependent upon the underlying OS, but there's gotta be some kind of default, and `tun0` was the default due to my personal workflows.  Docs look great, you nailed it, thank you for this!

**Comment by epi052** [comment]
merged
