### ISSUE TITLE
Add nuclei tool definition

### ISSUE THREAD

**Issue by epi052** [epi052/recon-pipeline#80]
Install command
- `GO111MODULE=on go get -u -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei`

Dependencies
- `[go]`

**Comment by GreaterGoodest** [comment]
This should be quick for me to do

**Comment by epi052** [comment]
Up to you if you want to grab it.  I'm going to make a feature branch for the project PRs

**Comment by epi052** [comment]
still have some issues to make :smile:
