### ISSUE TITLE
Update nuclei templates regularly

### ISSUE THREAD

**Issue by epi052** [epi052/recon-pipeline#81]
This one is up for thought/discussion.  Nuclei templates have been seeing updates pretty frequently.  In order to take advantage of them, we should issue 

`nuclei -update-templates -update-directory TOOLS_FOLDER`

The question is when/how.  It's relatively quick, we could spawn a thread and do it on startup silently.  We could prompt the user on startup, but that feels invasive.  Scan start w/ prompt might be ok...

Right now, i'm leaning toward a silent ninja update.  Open for debate/thought tho

**Comment by GreaterGoodest** [comment]
Silent update makes sense to me, maybe with the potential to disable it in some sort of config for the rare folks that would be bothered? Would be annoying to be prompted at each launch, and the vast majority would just allow it. Maybe just prompt something like "Allow automatic nuclei updates at startup?" the first time the user runs the tool. Store setting in tool dict. Might also be nice in that case to make it possible to adjust the setting with a command after the fact.

Another option is to make permission for all auto-updating for any tools in the future generic with a global "allow automatic updates" setting.

**Comment by epi052** [comment]
i like the auto update thing, but it feels like scope creep.  

i'd say press with ninja update and leave auto updates as a potential future improvement.  thoughts?
